--------------------------------------------------------
-- Archivo creado  - jueves-marzo-19-2015   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table PERSONA
--------------------------------------------------------

  CREATE TABLE "PRUEBA"."PERSONA" 
   (	"PERSONAID" NUMBER(6,0), 
	"NOMBRE" VARCHAR2(20 BYTE), 
	"APELLIDO_MAT" VARCHAR2(20 BYTE), 
	"APELLIDO_PAT" VARCHAR2(20 BYTE), 
	"DNI" NUMBER(8,0)
   ) PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
REM INSERTING into PRUEBA.PERSONA
SET DEFINE OFF;
Insert into PRUEBA.PERSONA (PERSONAID,NOMBRE,APELLIDO_MAT,APELLIDO_PAT,DNI) values ('1','Luis','Santa María','Ticlavilca','45448683');
Insert into PRUEBA.PERSONA (PERSONAID,NOMBRE,APELLIDO_MAT,APELLIDO_PAT,DNI) values ('2','Maria Yolita','Guerrero','Gonzales','45448683');
--------------------------------------------------------
--  DDL for Index PERSONA_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "PRUEBA"."PERSONA_PK" ON "PRUEBA"."PERSONA" ("PERSONAID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  Constraints for Table PERSONA
--------------------------------------------------------

  ALTER TABLE "PRUEBA"."PERSONA" ADD CONSTRAINT "PERSONA_PK" PRIMARY KEY ("PERSONAID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
 
  ALTER TABLE "PRUEBA"."PERSONA" MODIFY ("PERSONAID" NOT NULL ENABLE);

